POST http://localhost:5000/api/register
Content-Type: application/json

{
    "name": "Mary Jane",
    "email": "maryjane@gmail.com",
    "password": "123456"
}
###
POST http://localhost:5000/api/login
Content-Type: application/json

{
    "email": "maryjane@gmail.com",
    "password": "123456"
}
###
GET http://localhost:5000/api/transactions/latest?user=5f89b324e626b84260ea86f9
###
POST http://localhost:5000/api/transactions/add
Content-Type: application/json

{
     "moneyType": "Credit",
      "transactionType": "Expense",
      "category": "Accessories",
      "amount": "2999",
      "description": "Heels",
      "user_id": "5f89b324e626b84260ea86f9"
}
###
GET http://localhost:5000/api/transactions?user=5f89b324e626b84260ea86f9&filter=all&sort=desc&page=1
###
DELETE http://localhost:5000/api/transactions/delete
Content-Type: application/json

{
    "user_id": "5f89b324e626b84260ea86f9",
    "_id": "5f89e25f11f7e16529e68043"
}

