export const POST_TRANSACTION_REQUEST = 'POST_TRANSACTION_REQUEST'
export const POST_TRANSACTION_SUCCESS = 'POST_TRANSACTION_SUCCESS'
export const POST_TRANSACTION_FAILURE = 'POST_TRANSACTION_FAILURE'